version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.6.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run test
          command: python test.py

workflows:
  version: 2
  workflows:
    jobs:
      - test